### ISSUE TITLE
Make system call associated code 'safe'

### ISSUE THREAD

**Issue by Sl1mb0** [HOMS-OSS/perf-rust#35]
I keep reading about the security concerns as it relates to `perf_event_open()`; considering Rust's ability to write 'safe' code, there are two things I have noticed that I think we should make an effort to address at some point:

* crap ton of warnings regarding the use of `unsafe` code in the bindings generated by `bindgen`. I think something that is totally doable, which would also be a somewhat interesting problem to solve, would be first to deduce what is the 'safe' and 'Rust' version of all of the code that generates `unsafe` warnings when running `cargo test`. Then, included in the build script, is a parser that finds this unsafe code in `bindings/perf_event.rs` and rewrites it to be the safe version. 
* I have been reading that the `ioctl()` system call poses an inherent security risk because it takes variable arguments. There is a crate called [iocuddle](https://github.com/enarx/iocuddle), where they discuss these security considerations and the safe interface they designed for using the `ioctl()` number for a specific group. I am thinking that we could build something similar to what they have, but tweak it a bit obviously and keep it minimal since we are only worried about IO stuff that is related to `perf_event.h`.

I think that we should use this issue to address security concerns and how we should deal with them.

**Comment by Boursler** [comment]
Doing some quick research it looks like calls to an external language will always be unsafe: https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html#using-extern-functions-to-call-external-code. However, we can definitely add wrappings to create a safe abstraction over them and that is probably the way to go with those. I'm unsure if we need them directly in the bindings/ or if they can go along with a module for each syscall we would use that wraps it, for instance in `ioctl()` possibly in that constants.rs file or in another file in the same module that exports our call to `ioctl()`. It might be easier to do the latter and also make it easier to update/change.

Then I think we also have the security risks inherent in making system calls and interacting with these fd's that we will need to be careful about.

 Do you mind putting something together that sums up your findings on that topic and posting either to the wiki on github or to zulip? Maybe as a first PR to this issue you could also put together some sample code to demonstrate, in `ioctl()`?

Wdyt?

**Comment by Sl1mb0** [comment]
I will definitely focus on putting together some coherent research regarding this topic. 

There should be two layers of abstraction as opposed to one. So an  `Event` would be the first layer (cycles, for example). This layer would then use the next layer, which would be the safe wrappers around the unsafe system calls.


We need to design a consistent interface centered around the necessary system calls for performance monitoring, and then build for specific events on top of that.

For two reasons:

* high modularity, low coupling, easier to build on top of then performing a bunch of system calls.
* will add another layer of security on top of system call use.

Curious about your input.

**Comment by Sl1mb0** [comment]
As a base idea I will work on building one for `ioctl()`, and include examples alongside the declarations and definitions in the source file.

**Comment by Sl1mb0** [comment]
@Boursler Pushed most of the wrappers to my `dev` branch. Take a look and let me know what you think. Located in `src/event/ioctl.rs`.
