### ISSUE TITLE
Extend `perf test` with subtests, skipped tests, clean `test/mod.rs`

### ISSUE THREAD

**Issue by kagutaba256** [HOMS-OSS/perf-rust#49]
Turning the comment on https://github.com/HOMS-OSS/ruperf/issues/41#issuecomment-878712176 into it's own issue. I'll add subtests and skipped tests and also clean up `test/mod.rs`. After this, I'll make the tests from https://github.com/HOMS-OSS/ruperf/issues/41.

**Comment by kagutaba256** [comment]
skip support done and moved `test/mod.rs` to `test.rs` over at https://github.com/kagutaba256/ruperf/tree/perftest-skip. moving on to subtests now

**Comment by kagutaba256** [comment]
added subtest support, but skipping subtests will require a bit more work (with like, ugly lifetimes stuff), so i'll put it on the backburner for now.

waiting for https://github.com/HOMS-OSS/ruperf/pull/48 to clear before i make a pr, but it is on my perftest-skip branch

**Comment by Boursler** [comment]
48 has been approved, you can merge it anytime :)
