### ISSUE TITLE
Add SPDX short license identifier to files in repo

### ISSUE THREAD

**Issue by Boursler** [HOMS-OSS/perf-rust#77]
Into top of file please add: SPDX-License-Identifier: GPL-2.0
Sort of a general call to action that I'd like anyone to add to as they go so we're good for project deadline.
Feel free to check off this checklist when added:

- [ ] build.rs
- [ ] CONTRIBUTING.md
- [ ] whitepaper.tex
- [ ] examples/file-io.rs
- [ ] examples/fp-calc.rs
- [ ] src/main.rs
- [ ] src/stat.rs
- [ ] src/test.rs
- [ ] srs/gui.rs
- [ ] src/utils.rs
- [ ] src/bindings/mod.rs
- [ ] src/event/fd.rs
- [ ] src/event/mod.rs
- [ ] src/event/open.rs
- [ ] src/event/utils.rs
- [ ] src/event/sys/linux.rs
- [ ] src/event/sys/mod.rs
- [ ] src/event/sys/wrapper.rs
- [ ] src/event/utils.rs
- [ ] src/gui/pane_content.rs
- [ ] src/gui/perf_event.rs
- [ ] src/gui/save_state.rs
- [ ] src/gui/state.rs
- [ ] src/gui/style.rs
- [ ] src/test/basic.rs
- [ ] src/test/pfm.rs
- [ ] src/test/testutils.rs

Thanks!

**Comment by Sl1mb0** [comment]
I've got a branch where I have cleaned virtually all of our source files so I will just add this to my do list!
